### ISSUE TITLE
Add the correct description.

### ISSUE THREAD

**Issue by lk-geimfari** [lk-geimfari/exconsts#1]
@wikkiewikkie Can you help me with detailed description, please? I can't correctly describe this project with my English.

**Comment by wikkiewikkie** [comment]
@lk-geimfari I think you did pretty well.

> Exconsts is a library that allows you to load constants, such as your application configuration, from a JSON file.  The constants can be scoped to the entire module, or just a particular class.

I will take a look at the rest of the documentation later.

**Comment by lk-geimfari** [comment]
@wikkiewikkie Oh, good. Thank you very much!
